import { describe, it, expect, vi } from "vitest";
import fs from "fs";
import path from "path";

// ── Mocks ───────────────────────────────────────────────────

vi.mock("server-only", () => ({}));

vi.mock("next/navigation", () => ({
  redirect: vi.fn((url: string) => {
    throw new Error(`REDIRECT:${url}`);
  }),
}));

vi.mock("next/font/google", () => ({
  Geist: vi.fn(() => ({ variable: "--font-geist-sans", subsets: [] })),
  Geist_Mono: vi.fn(() => ({ variable: "--font-geist-mono", subsets: [] })),
  Space_Grotesk: vi.fn(() => ({
    variable: "--font-space-grotesk",
    subsets: [],
  })),
  Inter: vi.fn(() => ({ variable: "--font-inter", subsets: [] })),
}));

vi.mock("next/link", () => ({
  default: vi.fn(({ children, href, ...props }) => ({
    type: "a",
    props: { href, ...props, children },
  })),
}));

// ── Tests ───────────────────────────────────────────────────

describe("root layout metadata", () => {
  it("exports title as AutoApply", async () => {
    const { metadata } = await import("@/app/layout");
    expect(metadata.title).toBe("AutoApply");
  });

  it("exports a descriptive description", async () => {
    const { metadata } = await import("@/app/layout");
    expect(metadata.description).toContain("AI-powered resume builder");
  });

  it("does not contain default Create Next App text", async () => {
    const { metadata } = await import("@/app/layout");
    expect(metadata.title).not.toBe("Create Next App");
    expect(metadata.description).not.toBe("Generated by create next app");
  });
});

describe("not-found page", () => {
  it("exports a default function component", async () => {
    const mod = await import("@/app/not-found");
    expect(typeof mod.default).toBe("function");
  });

  it("is a server component (no use client directive)", async () => {
    const filePath = path.join(process.cwd(), "src/app/not-found.tsx");
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).not.toMatch(/^"use client"/m);
  });

  it("contains Page not found heading", async () => {
    const filePath = path.join(process.cwd(), "src/app/not-found.tsx");
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain("Page not found");
  });

  it("contains a home link to /", async () => {
    const filePath = path.join(process.cwd(), "src/app/not-found.tsx");
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain('href="/"');
  });
});

describe("root loading page", () => {
  it("exports a default function component", async () => {
    const mod = await import("@/app/loading");
    expect(typeof mod.default).toBe("function");
  });

  it("is a server component (no use client directive)", async () => {
    const filePath = path.join(process.cwd(), "src/app/loading.tsx");
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).not.toMatch(/^"use client"/m);
  });

  it("includes accessible loading status", async () => {
    const filePath = path.join(process.cwd(), "src/app/loading.tsx");
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain('role="status"');
    expect(content).toContain('aria-label="Loading"');
  });
});

describe("dashboard loading page", () => {
  it("exports a default function component", async () => {
    const mod = await import("@/app/dashboard/loading");
    expect(typeof mod.default).toBe("function");
  });

  it("is a server component (no use client directive)", async () => {
    const filePath = path.join(
      process.cwd(),
      "src/app/dashboard/loading.tsx",
    );
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).not.toMatch(/^"use client"/m);
  });
});

describe("error page", () => {
  it("exports a default function component", async () => {
    const mod = await import("@/app/error");
    expect(typeof mod.default).toBe("function");
  });

  it("begins with use client directive", async () => {
    const filePath = path.join(process.cwd(), "src/app/error.tsx");
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toMatch(/^"use client"/m);
  });

  it("accepts error and reset props", async () => {
    const filePath = path.join(process.cwd(), "src/app/error.tsx");
    const content = fs.readFileSync(filePath, "utf-8");
    // Verify the component signature accepts error and reset
    expect(content).toContain("reset: () => void");
    expect(content).toContain("onClick={reset}");
  });

  it("contains accessible retry button calling reset", async () => {
    const filePath = path.join(process.cwd(), "src/app/error.tsx");
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain("onClick={reset}");
    expect(content).toContain("Try again");
  });
});
